image: Visual Studio 2017

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache  # NuGet v3
  
platform:
  - x86
  - x64
  - Any CPU

configuration:
  - Debug
  - Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: NFSScript.sln          # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: detailed #normal/detailed
